### ISSUE TITLE
Nodes deployment failed - cannot go from state 'deploy failed' to state 'manageable'

### ISSUE THREAD

**Issue by itzikb10** [openshift-metal3/dev-scripts#617] opened 2019-06-13 08:01 UTC
**Describe the bug**
Using a virtualized setup (One hypervisor) installation fails 
```
level=error msg="Error: cannot go from state 'deploy failed' to state 'manageable'"
level=error
level=error msg="  on ../../../tmp/kni-install-626285310/masters/main.tf line 32, in resource \"ironic_deployment\" \"openshift-master-deployment\":"
level=error msg="  32: resource \"ironic_deployment\" \"openshift-master-deployment\" {"
level=error
```

Nodes are not deployed:
```
$ openstack baremetal node list
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID                        | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| 3fb3633e-a9c2-46d4-a4a2-ed97a986a5e4 | openshift-master-1 | a9259fab-272a-40de-ba01-07ab8b7da0b1 | power on    | deploy failed      | False       |
| 844a883d-420f-47a3-a5bb-4aaac01be488 | openshift-master-0 | 1917e8dd-38a9-4e7d-aa86-fbac75c7d56a | power on    | deploy failed      | False       |
| 66db8847-1b5b-4a8d-8b04-f4c336c29f22 | openshift-master-2 | 6b64c177-9d20-4759-a45a-72ce2cd2eaf0 | power on    | deploy failed      | False       |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
```

**From Ironic Logs**
```
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures [req-cda4b2fc-f28a-402c-b128-594299ef5ea7 - - - - -] exception calling callback for <Future at 0x7f59fa9d0290 state=finished returned NoneType>: NodeNotLocked: Node 3fb3633e-a9c2-46d4-a4a2-ed97a986a5e4 found not to be locked on release
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures Traceback (most recent call last):
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 301, in _invoke_callbacks
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     callback(self)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py", line 431, in _thread_release_resources
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     self.release_resources()
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/ironic/conductor/task_manager.py", line 346, in release_resources
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     objects.Node.release(self.context, CONF.host, self.node.id)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/ironic/objects/node.py", line 358, in release
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     cls.dbapi.release_node(tag, node_id)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 154, in wrapper
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     ectxt.value = e.inner_exc
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     self.force_reraise()
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     six.reraise(self.type_, self.value, self.tb)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/oslo_db/api.py", line 142, in wrapper
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     return f(*args, **kwargs)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures   File "/usr/lib/python2.7/site-packages/ironic/db/sqlalchemy/api.py", line 466, in release_node
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures     raise exception.NodeNotLocked(node=node.uuid)
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures NodeNotLocked: Node 3fb3633e-a9c2-46d4-a4a2-ed97a986a5e4 found not to be locked on release
/opt/dev-scripts/ironic/log/ironic/ironic-conductor.log:2019-06-13 07:33:54.231 74 ERROR concurrent.futures 
```

And
```
/opt/dev-scripts/ironic/log/mariadb/mariadb.log:2019-06-03  9:50:36 10 [Warning] Aborted connection 10 to db: 'ironic' user: 'ironic' host: 'localhost' (Got an error reading communication packets)
/opt/dev-scripts/ironic/log/mariadb/mariadb.log:2019-06-03  9:50:36 11 [Warning] Aborted connection 11 to db: 'ironic' user: 'ironic' host: 'localhost' (Got an error reading communication packets)
/opt/dev-scripts/ironic/log/mariadb/mariadb.log:2019-06-03  9:50:36 15 [Warning] Aborted connection 15 to db: 'ironic' user: 'ironic' host: 'localhost' (Got an error reading communication packets)
/opt/dev-scripts/ironic/log/mariadb/mariadb.log:2019-06-03  9:50:36 12 [Warning] Aborted connection 12 to db: 'ironic' user: 'ironic' host: 'localhost' (Got an error reading communication packets)
/opt/dev-scripts/ironic/log/mariadb/mariadb.log:2019-06-03  9:50:36 18 [Warning] Aborted connection 18 to db: 'ironic' user: 'ironic' host: 'localhost' (Got an error reading communication packets)
...
```

**Comment by hardys** [comment] 2019-06-13 08:07
I believe @cybertron has run into this and is investigating with the Ironic team

**Comment by cybertron** [comment] 2019-06-13 14:14
According to Julia, this may be because the system was overloaded during deployment. I know it gets noticeably laggy while the images are being copied due to the large amount of concurrent io happening.

I did notice that the kernel is detecting my storage as rotational, which is not correct. It's probably because of the RAID controller on the server. I'm experimenting with different io schedulers to see if that helps. It's possible the kernel is fighting with the controller in trying to optimize io. At least that's what I'm hoping. If a RAID0 of two ssds isn't fast enough to handle a dev environment I'm not sure what I'll do. :-)

**Comment by cybertron** [comment] 2019-06-13 18:05
Okay, still happening with other io schedulers. noop might have been a little better, but I did still ultimately hit this failure again.

I'm currently experimenting with bumping the Ironic heartbeat timeout. I added:

--env OS_CONDUCTOR__HEARTBEAT_TIMEOUT=120 \

to the podman invocation for ironic in script 04. Will run some test deployments and see if the problem still reproduces.

**Comment by hardys** [comment] 2019-07-01 08:49
Closed via https://github.com/openshift-metal3/dev-scripts/pull/622

**Closed by hardys** 2019-07-01 08:49 UTC
