### ISSUE TITLE
Make Clean fails with error Error: no such file or directory make: *** [ironic_cleanup] Error 125

### ISSUE THREAD

**Issue by suppawar** [openshift-metal3/dev-scripts#547] opened 2019-05-17 12:34 UTC
While trying to run 04_setup_ironic.sh file of devscripts I get below error.
---------------------------------
+ grep -w 'mariadb$'
+ sudo podman ps --all
+ grep -w 'mariadb$'
+ sudo podman pod exists ironic-pod
+ sudo podman pod rm ironic-pod -f
Error: no such file or directory
-----------------------------------------------
If I try to clean the installation with make clean, Then also it fails with same error.
Even If I try to delete pod and image it does not allowed to delete.
see below cmd outputs:

sudo podman ps --all
CONTAINER ID  IMAGE                 COMMAND  CREATED      STATUS   PORTS  NAMES
624486151a82  k8s.gcr.io/pause:3.1           3 weeks ago  Created         7a4ffe37566b-infra

sudo podman rm -a
Error: container 624486151a8249d9141e19f197f6ef52510b953df69b55d8c4e8cb65645406fd is the infra container of pod 7a4ffe37566b6d7864947ec830c79e55ea785483a6a6ec6b72fc0ffe0f6f5a83 and cannot be removed without removing the pod

sudo podman rmi --all --force
Error: error removing image da86e6ba6ca197bf6bc5e9d900febd906b133eaa4750e6bed647b0fbe50ed43e: container 624486151a8249d9141e19f197f6ef52510b953df69b55d8c4e8cb65645406fd using image could not be removed: container 624486151a8249d9141e19f197f6ef52510b953df69b55d8c4e8cb65645406fd is the infra container of pod 7a4ffe37566b6d7864947ec830c79e55ea785483a6a6ec6b72fc0ffe0f6f5a83 and cannot be removed without removing the pod

**Comment by hardys** [comment] 2019-05-17 12:41
This is a duplicate of https://github.com/openshift-metal3/dev-scripts/issues/374 - there are some workarounds and an upstream podman bug linked there

**Closed by hardys** 2019-05-17 12:41 UTC
