### ISSUE TITLE
ipa-downloader on bootrap vm exits with rc 2 and doesn't output any logs

### ISSUE THREAD

**Issue by mcornea** [openshift-metal3/dev-scripts#747] opened 2019-08-19 14:59 UTC
**Describe the bug**
Deployment exits with msg="Error: could not contact API: timeout reached"

Trying to debug I log in to the bootstrap VM where I can see the ipa-downloader container exited with rc 2 but the logs do not show any info so it's hard to tell what went wrong:

```shell
[root@localhost core]# podman ps -a |  grep ipa-downloader
bb79a565460d  quay.io/metal3-io/ironic-ipa-downloader:master                                                                          /usr/local/bin/ge...  21 minutes ago  Exited (2) 7 minutes ago          ipa-downloader
[root@localhost core]# 
[root@localhost core]# 
[root@localhost core]# podman logs ipa-downloader
[root@localhost core]# podman logs bb79a565460d
[root@localhost core]# 
```

**Expected/observed behavior**
ipa-downloader container doesn't output any logs. In order to troubleshoot failures we need to be able to see the logs of failing containers.

**Comment by mcornea** [comment] 2019-08-19 16:21
I tried reproducing the issue and this time the container exited successfully and the logs are accessible:

```shell
[root@localhost core]# podman ps -a | grep ipa-downloader
1f77df2cbd22  quay.io/metal3-io/ironic-ipa-downloader:master                                                                          /usr/local/bin/ge...  38 minutes ago  Exited (0) 6 minutes ago          ipa-downloader
[root@localhost core]# podman logs ipa-downloader
+ SNAP=current-tripleo-rdo
+ FILENAME=ironic-python-agent
+ FILENAME_EXT=.tar
+ FFILENAME=ironic-python-agent.tar
++ mktemp -d
+ TMPDIR=/tmp/tmp.Ud9LAYZzrz
+ mkdir -p /shared/html/images
+ cd /shared/html/images
+ ls -l
total 0
+ '[' -n http://192.168.123.1/images -a '!' -e ironic-python-agent.tar.headers ']'
+ curl --fail -O http://192.168.123.1/images/ironic-python-agent.tar.headers
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0 
+ true
+ '[' -e ironic-python-agent.tar.headers ']'
+ cd /tmp/tmp.Ud9LAYZzrz
+ curl --dump-header ironic-python-agent.tar.headers -O https://images.rdoproject.org/stein/rdo_trunk/current-tripleo-rdo/ironic-python-agent.tar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  291M  100  291M    0     0   155k      0  0:31:53  0:31:53 --:--:--  100k
+ '[' -s ironic-python-agent.tar ']'
+ tar -xf ironic-python-agent.tar
++ awk '/ETag:/ {print $2}' ironic-python-agent.tar.headers
++ tr -d '"\r'
+ ETAG=12359000-590677acf7200
+ cd -
/shared/html/images
+ chmod 755 /tmp/tmp.Ud9LAYZzrz
+ mv /tmp/tmp.Ud9LAYZzrz ironic-python-agent-12359000-590677acf7200
+ ln -sf ironic-python-agent-12359000-590677acf7200/ironic-python-agent.tar.headers ironic-python-agent.tar.headers
+ ln -sf ironic-python-agent-12359000-590677acf7200/ironic-python-agent.initramfs ironic-python-agent.initramfs
+ ln -sf ironic-python-agent-12359000-590677acf7200/ironic-python-agent.kernel ironic-python-agent.kernel
```

**Comment by jtaleric** [comment] 2019-08-19 16:27
To get past this I applied @rdoxenham 's patch locally.

**Comment by russellb** [comment] 2019-08-19 21:48
which patch?

**Comment by hardys** [comment] 2019-08-20 09:09
I believe the patch is the installer fix for https://github.com/openshift/installer/issues/2232 (https://github.com/openshift/installer/pull/2239 is the proposed fix)

Since it's clear from the report that we're not using the provisioning IP on the host, I think this can be closed as a duplicate of https://github.com/openshift-metal3/dev-scripts/issues/748 which was also closed since we've got the installer issue above to track resolution of this problem with the CACHEURL

**Closed by hardys** 2019-08-20 09:09 UTC
