### ISSUE TITLE
Ironic fails to adopt bare metal hosts

### ISSUE THREAD

**Issue by cynepco3hahue** [openshift-metal3/dev-scripts#736] opened 2019-08-14 14:40 UTC
**Describe the bug**
After running `make` deployment finishes, but under the ironic I can see that adopt failed, and updating `spec.online` does not poweroff and poweron the host.

```
openstack baremetal node list
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| d8b6003f-84a8-40c8-869f-ec4d4780cedd | openshift-master-0 | None          | power on    | adopt failed       | False       |
| 8318f30d-91ef-4ce6-823f-206b5d5d202d | openshift-master-1 | None          | power on    | adopt failed       | False       |
| 9514e80b-501a-4311-9f8d-303017ac9125 | openshift-master-2 | None          | power on    | adopt failed       | False       |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
```

**To Reproduce**
Run `make` from the master.
I used config
```
# cat config_root.sh 
#!/bin/bash

# Get a valid pull secret (json string) from
# You can get this secret from https://cloud.openshift.com/clusters/install#pull-secret
set +x
export PULL_SECRET='...'
set -x

# Uncomment to build a copy of ironic or inspector locally
#export IRONIC_INSPECTOR_IMAGE=https://github.com/metal3-io/ironic-inspector
#export IRONIC_IMAGE=https://github.com/metal3-io/ironic

# SSH key used to ssh into deployed hosts.  This must be the contents of the
# variable, not the filename. The contents of ~/.ssh/id_rsa.pub are used by
# default.
export SSH_PUB_KEY=$(cat ~/.ssh/id_rsa.pub)

# Configure custom ntp servers if needed
#export NTP_SERVERS="00.my.internal.ntp.server.com;01.other.ntp.server.com"
NUM_WORKERS=0
CLUSTER_NAME=demo
BASE_DOMAIN=test.beekhof.net
```

**Expected/observed behavior**
I think hosts under the ironic should have adopted state and updating `spec.Online` should power off and power on the host.

**Additional context**
```
# oc -n openshift-machine-api get bmh
NAME                 STATUS   PROVISIONING STATUS      CONSUMER        BMC                         HARDWARE PROFILE   ONLINE   ERROR
openshift-master-0   OK       externally provisioned   demo-master-0   ipmi://192.168.111.1:6230                      true     
openshift-master-1   OK       externally provisioned   demo-master-1   ipmi://192.168.111.1:6231                      true     
openshift-master-2   OK       externally provisioned   demo-master-2   ipmi://192.168.111.1:6232                      false 
```
```
# virsh list
 Id    Name                           State
----------------------------------------------------
 112   openshift_master_1             running
 113   openshift_master_0             running
 114   openshift_master_2             running
```

**Comment by cynepco3hahue** [comment] 2019-08-14 14:46
Do not sure if it related but I also have some traceback under the `ironic-inspector`
```
# oc -n openshift-machine-api logs metal3-baremetal-operator-7469cd5f89-4vffk -c ironic-inspector
2019-08-14 14:44:31.581 1 WARNING ironicclient.common.http [-] HTTPClient class is deprecated and will be removed in Stein release, please use SessionClient instead.
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager [-] Periodic sync of node list with ironic failed: InvalidURL: Invalid URL u'http://:6385/v1': No host supplied
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager Traceback (most recent call last):
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironic_inspector/conductor/manager.py", line 149, in periodic_clean_up
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     sync_with_ironic()
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironic_inspector/conductor/manager.py", line 157, in sync_with_ironic
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     ironic_nodes = ironic.node.list(limit=0)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/v1/node.py", line 163, in list
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     os_ironic_api_version=os_ironic_api_version)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/base.py", line 162, in _list_pagination
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     resp, body = self.api.json_request('GET', url, **kwargs)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 500, in json_request
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     resp, body_iter = self._http_request(url, method, **kwargs)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 291, in wrapper
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     return func(self, url, method, **kwargs)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 421, in _http_request
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     self.negotiate_version(self.session, None)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 149, in negotiate_version
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     resp = _query_server(conn)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 121, in _query_server
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     return self._make_simple_request(conn, 'GET', base_version)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/ironicclient/common/http.py", line 409, in _make_simple_request
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     return conn.request(method, self._make_connection_url(url))
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 519, in request
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     prep = self.prepare_request(req)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 462, in prepare_request
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     hooks=merge_hooks(request.hooks, self.hooks),
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/requests/models.py", line 313, in prepare
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     self.prepare_url(url, params)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager   File "/usr/lib/python2.7/site-packages/requests/models.py", line 390, in prepare_url
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager     raise InvalidURL("Invalid URL %r: No host supplied" % url)
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager InvalidURL: Invalid URL u'http://:6385/v1': No host supplied
2019-08-14 14:44:31.583 1 ERROR ironic_inspector.conductor.manager
```

**Comment by derekhiggins** [comment] 2019-08-14 15:04
Looks like this is the problem in the inspector container

[root@master-1 ironic-inspector]# grep endpoint_override inspector.conf
endpoint_override = http://:6385

The IP is missing, which comes from $PROVISIONING_IP
runironic-inspector.sh:crudini --set $CONFIG ironic endpoint_override http://$PROVISIONING_IP:6385

Which comes from $PROVISIONING_INTERFACE
runironic-inspector.sh:PROVISIONING_IP=$(ip -4 address show dev "$PROVISIONING_INTERFACE" | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)

When I run this code inside the inspector container currently running, I get this

```
+ PROVISIONING_INTERFACE=ens3
+ CONFIG=/etc/ironic-inspector/inspector.conf
++ ip -4 address show dev ens3
++ grep -oP '(?<=inet\s)\d+(\.\d+){3}'
++ head -n 1
+ PROVISIONING_IP=172.22.0.3
+ echo crudini --set /etc/ironic-inspector/inspector.conf ironic endpoint_override http://172.22.0.3:6385
crudini --set /etc/ironic-inspector/inspector.conf ironic endpoint_override http://172.22.0.3:6385

```

So the IP address setting is working, I wonder if its possible the IP wasn't there when the container started?

**Comment by derekhiggins** [comment] 2019-08-14 15:14
ok, it looks to me like we have 2 containers that set the IP on the PROV_INTERFACE, initially by "static-ip-set" and then by "static-ip-refresh" every 5 seconds, so I guess there are cases where the interface looses its IP address, @imain is it possible that whats going on here? Are there conditions where the IP address is lost?

**Comment by cynepco3hahue** [comment] 2019-08-14 15:16
I know that MAO currently installs the BMO containers, so maybe it misses some configuration.

**Comment by hardys** [comment] 2019-08-14 15:31
> I know that MAO currently installs the BMO containers, so maybe it misses some configuration.

Note that until https://github.com/openshift-metal3/dev-scripts/pull/726 lands we're not actually using the MAO integration, so the BMO still gets launched by dev-scripts

**Comment by hardys** [comment] 2019-08-14 15:33
> ok, it looks to me like we have 2 containers that set the IP on the PROV_INTERFACE, initially by "static-ip-set" and then by "static-ip-refresh" every 5 seconds, so I guess there are cases where the interface looses its IP address, @imain is it possible that whats going on here? Are there conditions where the IP address is lost?

AFAIK it should never lose the IP unless the pod gets rescheduled, because we refresh the IP every 5 seconds with a 10 second lifetime

https://github.com/openshift/ironic-static-ip-manager/blob/master/refresh-static-ip#L19

Perhaps we should add some debug logging to the container to prove there's no long delays interrupting that loop, e.g print the status of the interface if it's down as a warning at the start of the loop or something?

**Comment by derekhiggins** [comment] 2019-08-14 15:43
> AFAIK it should never lose the IP unless the pod gets rescheduled, because we refresh the IP every 5 seconds with a 10 second lifetime

I guess is possible if the "static-ip-refresh" container starts 5 minutes after "static-ip-set" (which sets it for 5 minutes)

in this case it looks like it was 12 minutes
```
[root@master-1 core]# journalctl | grep -i "Started container static-ip-"
Aug 14 14:12:53 master-1 hyperkube[1222]: I0814 14:12:53.347177    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.initContainers{static-ip-set}"}): type: 'Normal' reason: 'Started' Started container static-ip-set
Aug 14 14:24:32 master-1 hyperkube[1222]: I0814 14:24:32.285797    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.containers{static-ip-refresh}"}): type: 'Normal' reason: 'Started' Started container static-ip-refresh
[root@master-1 core]# 

```

> https://github.com/openshift/ironic-static-ip-manager/blob/master/refresh-static-ip#L19
> 
> Perhaps we should add some debug logging to the container to prove there's no long delays interrupting that loop, e.g print the status of the interface if it's down as a warning at the start of the loop or something?

ya, it wouldn't do any harm

**Comment by derekhiggins** [comment] 2019-08-14 15:57
ok, the delay is downloading the container images

3.5 minutes for ironic-insoector image
```
Aug 14 14:20:59 master-1 hyperkube[1222]: I0814 14:20:59.541293    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.containers{ironic-inspector}"}): type: 'Normal' reason: 'Pulling' Pulling image "quay.io/metal3-io/ironic-inspector:master"
Aug 14 14:24:29 master-1 hyperkube[1222]: I0814 14:24:29.359864    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.containers{ironic-inspector}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "quay.io/metal3-io/ironic-inspector:master"

```
7 minutes for ironic
```
Aug 14 14:13:35 master-1 hyperkube[1222]: I0814 14:13:35.309865    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.containers{ironic-dnsmasq}"}): type: 'Normal' reason: 'Pulling' Pulling image "quay.io/metal3-io/ironic:master"
Aug 14 14:20:47 master-1 hyperkube[1222]: I0814 14:20:47.476109    1222 event.go:209] Event(v1.ObjectReference{Kind:"Pod", Namespace:"openshift-machine-api", Name:"metal3-baremetal-operator-7469cd5f89-4vffk", UID:"86b8c136-be9d-11e9-aa85-00e273a2437a", APIVersion:"v1", ResourceVersion:"14909", FieldPath:"spec.containers{ironic-dnsmasq}"}): type: 'Normal' reason: 'Pulled' Successfully pulled image "quay.io/metal3-io/ironic:master"
```


@imain Is there any downside to increasing the timeout (from 300) on the IP in set-static-ip ?

**Comment by derekhiggins** [comment] 2019-08-14 16:31
@cynepco3hahue want to try this 
https://github.com/openshift-metal3/dev-scripts/pull/737

**Comment by cynepco3hahue** [comment] 2019-08-15 06:37
tried with the PR, still his the sane output under the ironic
```
[root@had-01 dev-scripts]# openstack baremetal node list
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| 59be1af6-fdc5-40a5-8483-78aaa02d4efd | openshift-master-1 | None          | power on    | adopt failed       | False       |
| c5dab2b8-4fce-4f9e-84b1-36a6c7a1b336 | openshift-master-2 | None          | power on    | adopt failed       | False       |
| d7747117-b899-4201-b935-244e6f64cf64 | openshift-master-0 | None          | power on    | adopt failed       | False       |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
```

**Comment by hardys** [comment] 2019-08-15 07:58
> @imain Is there any downside to increasing the timeout (from 300) on the IP in set-static-ip ?

Do we actually need to set the provisioning IP in the initContainers section at all?  I'm thinking nothing actually uses it until ironic starts up, because the downloader containers can download from the external network, so we could drop static-ip-set, and ensure the refresh is the first thing that happens in the "containers" list?

**Comment by derekhiggins** [comment] 2019-08-15 08:50
with #737 on the env we;ve been using this inspector error didn't reproduce but we now have a new error, so I think there is two problems, the new error is in the ironic logs

2019-08-14 17:36:55.014 1 ERROR ironic.conductor.manager [req-a3527a53-c903-4bb3-9eb1-6ad58d8066f6 - - - - -] Error while attempting to adopt node 59be1af6-fdc5-40a5-8483-78aaa02d4efd: Cannot validate image information for node 59be1af6-fdc5-40a5-8483-78aaa02d4efd because one or more parameters are missing from its instance_info and insufficent information is present to boot from a remote volume. Missing are: ['ramdisk', 'kernel', 'image_source'].: MissingParameterValue: Cannot validate image information for node 59be1af6-fdc5-40a5-8483-78aaa02d4efd because one or more parameters are missing from its instance_info and insufficent information is present to boot from a remote volume. Missing are: ['ramdisk', 'kernel', 'image_source']

> > @imain Is there any downside to increasing the timeout (from 300) on the IP in set-static-ip ?
> 
> Do we actually need to set the provisioning IP in the initContainers section at all? I'm thinking nothing actually uses it until ironic starts up, because the downloader containers can download from the external network, so we could drop static-ip-set, and ensure the refresh is the first thing that happens in the "containers" list?

Yup this seems correct, the important thing is that the IP is there before the various ironic containers start.

**Comment by derekhiggins** [comment] 2019-08-15 09:54
Digging into why the node doesn't have the ramdisk/kernel info I found

failed to find existing host: failed to find node by name openshift-master-1: Get http://172.22.0.3:6385/v1/nodes/openshift-master-1: dial tcp 172.22.0.3:6385: connect: connection refused"

it looks like the BMO tried to registered the nodes 33 times from 'Wed Aug 14 18:35:44 2019' to 'Wed Aug 14 18:36:25 2019'

and the ironic-api containter stared 20 seconds after the last attempt

**Comment by cynepco3hahue** [comment] 2019-08-15 11:48
Checked with latest PR rotation, still the same result
```
[root@had-01 dev-scripts]# openstack baremetal node list
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
| 3edd6e95-52bd-477b-931e-bf498d8b3273 | openshift-master-0 | None          | power on    | adopt failed       | False       |
| 1e42f808-5db5-4683-a796-efce56713720 | openshift-master-1 | None          | power on    | adopt failed       | False       |
| f5aaaad1-2252-4aa1-8727-e4c333c2d024 | openshift-master-2 | None          | power on    | adopt failed       | False       |
+--------------------------------------+--------------------+---------------+-------------+--------------------+-------------+
```

**Comment by dhellmann** [comment] 2019-08-15 13:15
The adoption code is currently broken. I'm working on fixing it, starting with https://github.com/metal3-io/baremetal-operator/pull/278. There will be a few other follow-up changes to the cluster-api-provider and the installer.

**Comment by derekhiggins** [comment] 2019-08-15 13:41
> The adoption code is currently broken. I'm working on fixing it, starting with [metal3-io/baremetal-operator#278](https://github.com/metal3-io/baremetal-operator/pull/278). There will be a few other follow-up changes to the cluster-api-provider and the installer.

Ack, thanks, I guess this is the patch we need
https://github.com/metal3-io/baremetal-operator/pull/278/commits/6d84bf10f2a45b999e1e58881e8d2355dc0e6776

Also not that #737 did get rid of two of the other problems discussed in this issue so I think we should probably go ahead with changing the order of the containers

**Comment by dhellmann** [comment] 2019-08-15 14:19
> > The adoption code is currently broken. I'm working on fixing it, starting with [metal3-io/baremetal-operator#278](https://github.com/metal3-io/baremetal-operator/pull/278). There will be a few other follow-up changes to the cluster-api-provider and the installer.
> 
> Ack, thanks, I guess this is the patch we need
> [metal3-io/baremetal-operator@6d84bf1](https://github.com/metal3-io/baremetal-operator/commit/6d84bf10f2a45b999e1e58881e8d2355dc0e6776)

That's part of it. Masters don't have the values that patch uses, so we need to fix that, too. I need the BMO change to land before I can land the other changes, though.

> Also not that #737 did get rid of two of the other problems discussed in this issue so I think we should probably go ahead with changing the order of the containers

I agree. There are several problems described in this one issue. I'm tracking the "adopt failed" thing separately, so we can concentrate on the container stuff here.

**Comment by dhellmann** [comment] 2019-08-23 18:50
https://github.com/metal3-io/baremetal-operator/pull/278 should have fixed this. Are you still seeing this problem, @cynepco3hahue ?

**Comment by hardys** [comment] 2019-08-29 11:08
This is fixed in recent releases, so closing this issue:

```
$ oc get nodes
NAME       STATUS   ROLES           AGE    VERSION
master-0   Ready    master,worker   171m   v1.14.0+a90a3a923
master-1   Ready    master,worker   171m   v1.14.0+a90a3a923
master-2   Ready    master,worker   171m   v1.14.0+a90a3a923

$ oc get bmh --namespace openshift-machine-api
NAME                 STATUS   PROVISIONING STATUS      CONSUMER                BMC                         HARDWARE PROFILE   ONLINE   ERROR
openshift-master-0   OK       externally provisioned   ostest-master-0         ipmi://192.168.111.1:6230                      true     
openshift-master-1   OK       externally provisioned   ostest-master-1         ipmi://192.168.111.1:6231                      true     
openshift-master-2   OK       externally provisioned   ostest-master-2         ipmi://192.168.111.1:6232                      true     
openshift-worker-0   OK       provisioned              ostest-worker-0-vwtcg   ipmi://192.168.111.1:6233   unknown            true     

$ openstack baremetal node list
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID                        | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| 43fdd99e-9d7e-4489-a1a9-08202c9fbbb4 | openshift-master-0 | 43fdd99e-9d7e-4489-a1a9-08202c9fbbb4 | power on    | active             | False       |
| bd95518c-5899-4dc8-82e6-3ce5e047a8e5 | openshift-master-1 | bd95518c-5899-4dc8-82e6-3ce5e047a8e5 | power on    | active             | False       |
| dab06f22-179b-44bb-bd15-a48ce08a614d | openshift-master-2 | dab06f22-179b-44bb-bd15-a48ce08a614d | power on    | active             | False       |
| 8706af09-f1d5-46f0-bb0f-b269d94f3b7f | openshift-worker-0 | 8706af09-f1d5-46f0-bb0f-b269d94f3b7f | power on    | active             | False       |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+

```

**Closed by hardys** 2019-08-29 11:08 UTC
