### ISSUE TITLE
IRONIC_MACHINE_OS_DOWNLOADER_IMAGE unable to  gzip -d image 

### ISSUE THREAD

**Issue by nikita133** [openshift-metal3/dev-scripts#870] opened 2019-12-20 14:34 UTC
**Describe the bug**
IRONIC_MACHINE_OS_DOWNLOADER_IMAGE=registry.svc.ci.openshift.org/ocp/4.4-2019-12-19-033827@sha256:e0ae053ac41a424b4f18702574e42dbb0bac48b13cc0356880272ae9df843354
After image( rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz) is downloaded, container tries to open archive however image is not in gzip format. This is usual not compressed qcow2 file. As a result container exits with error  "Exited (1)"

Logs:
+ gzip -d rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz
gzip: rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz: not in gzip format

file /opt/dev-scripts/ironic/tmp/tmp.AZMCKV6OJu/rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz
/opt/dev-scripts/ironic/tmp/tmp.AZMCKV6OJu/rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz: QEMU QCOW Image (v3), 17179869184 bytes

**To Reproduce**
Run script:
04_setup_ironic.sh
and this script ends by infinity loop
 curl --fail http://localhost/images/rhcos-ootpa-latest.qcow2.md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
sleep 1

Check container logs 
podman logs d25add5520c9
+ gzip -d rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz
gzip: rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz: not in gzip format

Environment: VMs
No customization at all. All env.variables are default except PULL_SECRET

**Expected/observed behavior**
1) Compress image rhcos-44.81.201912131839.0-openstack.x86_64.qcow2.gz

**Comment by hardys** [comment] 2019-12-20 14:51
This was fixed yesterday via  https://github.com/openshift-metal3/dev-scripts/pull/867

The problem is the Content-Encoding header was reintroduced, now fixed via https://github.com/coreos/coreos-assembler/pull/1006 but #867 works around the issue by downloading the images without the --compressed flag

**Closed by hardys** 2019-12-20 14:51 UTC
