### ISSUE TITLE
Removal of Extra Route on Bootstrap VM to Complete Install

### ISSUE THREAD

**Issue by schmaustech** [openshift-metal3/dev-scripts#494] opened 2019-05-01 12:19 UTC
**Describe the bug**
During the installation of the OCP cluster when the bootstrap VM is instantiated multiple routes for the external network appear in the routing table for the same interface:

[core@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0a:8f:f4:a9:93:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.246/24 brd 192.168.0.255 scope global dynamic noprefixroute ens3
       valid_lft 564sec preferred_lft 564sec
    **inet 192.168.0.247/24 brd 192.168.0.255 scope global secondary dynamic noprefixroute ens3**
       valid_lft 413sec preferred_lft 413sec
    inet6 fe80::88f:f4ff:fea9:93ee/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:78:f3:7d:00:cf brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.13/24 brd 172.22.0.255 scope global dynamic noprefixroute ens4
       valid_lft 3566sec preferred_lft 3566sec
    inet 172.22.0.12/24 brd 172.22.0.255 scope global secondary dynamic noprefixroute ens4
       valid_lft 3423sec preferred_lft 3423sec
    inet6 fe80::f878:f3ff:fe7d:cf/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

[core@localhost ~]$ ip route
default via 192.168.0.1 dev ens3 
default via 192.168.0.1 dev ens3 proto dhcp metric 100 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.12 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.13 metric 101 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.12 metric 101 
**192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.247** 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.246 metric 100 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.247 metric 100

The route in bold above causes the bootstrap VM to be unable to reach any of the master node IPs on the network and must be removed early in the cluster deploy process.  I have been removing it while the master nodes are getting RHCOS deployed.

[core@localhost ~]$ sudo ip route del 192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.247
[core@localhost ~]$ ip route
default via 192.168.0.1 dev ens3 
default via 192.168.0.1 dev ens3 proto dhcp metric 100 
10.88.0.0/16 dev cni0 proto kernel scope link src 10.88.0.1 linkdown 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.12 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.13 metric 101 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.12 metric 101 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.246 metric 100 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.247 metric 100

I also would like to note that after awhile when the RHCOS masters are configuring and coming online the IP address with the odd route, in this example 192.168.0.247, also goes away from the ens3 interface without any additional intervention:

ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0a:8f:f4:a9:93:ee brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.246/24 brd 192.168.0.255 scope global dynamic noprefixroute ens3
       valid_lft 340sec preferred_lft 340sec
    inet 192.168.0.199/24 scope global secondary ens3
       valid_lft forever preferred_lft forever
    inet 192.168.0.198/24 scope global secondary ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::88f:f4ff:fea9:93ee/64 scope link noprefixroute 

**To Reproduce**
-This is a baremetal install with bootstrap VM running on a Centos laptop with an external interface and a provisioning interface.
-Pull fresh master of dev-scripts as of April 30th
-Run through installation as normal

**Expected/observed behavior**
I would expect I would not have to monitor install and remove extra route during the installation process.

**Additional context**

**Comment by yboaron** [comment] 2019-05-01 15:10
@schmaustech ,

Does 192.168.0.246 is the main IP (set by DHCP) address of the bootstrap VM? 

Could you please :
     * specify what IPs are used for the API and DNS VIPs?
     * add the output of ping command from bootstrap VM to one of the masters IPs (before u delete the problematic route)

**Comment by schmaustech** [comment] 2019-05-01 17:04
Here is some clarity on env layout:

api IP: 192.168.0.199
ns1 IP: 192.168.0.198
master-0: 192.168.0.200
master-1: 192.168.0.201
master-2: 192.168.0.202

In that last example .246 was the main address on bootstrap VM.  The centos host gets .206 always.

To get the route ping information you want I will need to rerun a deploy.

**Comment by schmaustech** [comment] 2019-05-01 18:22
**[core@localhost ~]$ ping 192.168.0.200
connect: Invalid argument**
[core@localhost ~]$ ip r
default via 192.168.0.1 dev ens3 
default via 192.168.0.1 dev ens3 proto dhcp metric 100 
10.88.0.0/16 dev cni0 proto kernel scope link src 10.88.0.1 linkdown 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.50 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.51 metric 101 
172.22.0.0/24 dev ens4 proto kernel scope link src 172.22.0.50 metric 101 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.249 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.248 metric 100 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.249 metric 100 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.199 metric 100 
192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.198 metric 100 
[core@localhost ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 56:c7:b6:49:9b:ce brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.248/24 brd 192.168.0.255 scope global dynamic noprefixroute ens3
       valid_lft 554sec preferred_lft 554sec
    inet 192.168.0.199/24 scope global secondary ens3
       valid_lft forever preferred_lft forever
    inet 192.168.0.198/24 scope global secondary ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::54c7:b6ff:fe49:9bce/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 7e:eb:69:26:40:9c brd ff:ff:ff:ff:ff:ff
    inet 172.22.0.51/24 brd 172.22.0.255 scope global dynamic noprefixroute ens4
       valid_lft 3090sec preferred_lft 3090sec
    inet 172.22.0.50/24 brd 172.22.0.255 scope global secondary dynamic noprefixroute ens4
       valid_lft 2942sec preferred_lft 2942sec
    inet6 fe80::7ceb:69ff:fe26:409c/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
4: cni0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 2a:15:41:d2:52:d6 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.1/16 scope global cni0
       valid_lft forever preferred_lft forever
    inet6 fe80::2815:41ff:fed2:52d6/64 scope link 
       valid_lft forever preferred_lft forever
[core@localhost ~]$ ping 192.168.0.201
connect: Invalid argument
**[core@localhost ~]$ ping 192.168.0.202
connect: Invalid argument**
[core@localhost ~]$ sudo ip route del 192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.249
[core@localhost ~]$ ping 192.168.0.202
PING 192.168.0.202 (192.168.0.202) 56(84) bytes of data.
64 bytes from 192.168.0.202: icmp_seq=1 ttl=64 time=0.686 ms
64 bytes from 192.168.0.202: icmp_seq=2 ttl=64 time=0.959 ms
^C
--- 192.168.0.202 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 65ms
rtt min/avg/max/mdev = 0.686/0.822/0.959/0.139 ms
[core@localhost ~]$ ping 192.168.0.201
PING 192.168.0.201 (192.168.0.201) 56(84) bytes of data.
64 bytes from 192.168.0.201: icmp_seq=1 ttl=64 time=0.617 ms
64 bytes from 192.168.0.201: icmp_seq=2 ttl=64 time=0.789 ms
^C
--- 192.168.0.201 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 4ms
rtt min/avg/max/mdev = 0.617/0.703/0.789/0.086 ms
[core@localhost ~]$ ping 192.168.0.200
PING 192.168.0.200 (192.168.0.200) 56(84) bytes of data.
64 bytes from 192.168.0.200: icmp_seq=1 ttl=64 time=0.515 ms
^C

**Comment by yboaron** [comment] 2019-05-02 13:24
@schmaustech - 10x for the details.
So, in the latest example, you paste above,
To communicate with 192.168.0.0/24 subnet we should use
'192.168.0.0/24 dev ens3 proto kernel scope link src 192.168.0.249'  route.
This is the route with the highest metric (metric not specified --> means metric=0)

But I can't see 192.168.0.249 in the 'ip a' list under ens3.

That may explain why you can't ping the external subnet from the bootstrap node.

But we should understand why '192.168.0.249' is missing from your 'ip a' in your env

**Comment by yboaron** [comment] 2019-05-06 21:42
@schmaustech 
I looked deeply into this issue and this is what I found so far.
To reproduce it,  I stopped the deployment (virtual dev-scripts) after the bootstrap node was created and sshed to bootstrap node for debugging.

A. So, it seems that two IP addresses are allocated (DHCP) for the Provision and Baremetal networks. 
First IP is requested (DHCP) by dracut
Second IP requested by NetworkManager
Btw both DHCP requests use the same MAC address.

And also two routing entries are created for each subnet, see [1].
The route that used the IP allocated at dracut phase ar src, is set with higher metric (no metric is specified), for example:
192.168.111.0/24 dev ens3 proto kernel scope link src 192.168.111.43

Till here, we just allocate extra IP (which is a bug) for both provision and baremetal subnets, but we are able to communicate with hosts in the baremetal subnet.

B.  After DHCP lease timeout is expired the IP address allocated at dracut (i.e : 192.168.111.43) is deleted, but the corresponding route is not deleted.
And as a result of that it is impossible to communicate with hosts (masters) on the baremetal subnet.

I guess that you hit this bug, since the time it takes for your BM servers to start is longer than the DHCP lease time. 

Could you please try to increase the DHCP lease timeout in your setup and see if it WA the problem for you?

**Comment by yboaron** [comment] 2019-05-07 11:30
see #512

**Comment by schmaustech** [comment] 2019-05-15 12:25
So the original lease time was 600 (10min).  I upped it to 1000 (~16mins) and still saw the extra route.  Are we thinking we need a 2 hour lease time or more?

**Comment by hardys** [comment] 2019-07-08 09:36
Can we close this issue and track resolution via #512 ?

**Comment by yboaron** [comment] 2019-07-08 11:24
@hardys , Yes, we can close this issue.

**Closed** 2019-07-08 11:25 UTC
