### ISSUE TITLE
Unable to query ironic inspector for data

### ISSUE THREAD

**Issue by achuzhoy** [openshift-metal3/dev-scripts#679] opened 2019-07-19 19:17 UTC
ironic inspector pod doesn't appear to be running on masters (and it's not available on provisionhost anymore).

Need to be able to query ironic inspector for introspection data.

[cloud-user@r640-u01 dev-scripts]$ OS_URL=http://openshift-master-2.qe1.kni.lab.eng.bos.redhat.com:5050 openstack baremetal introspection data save openshift-master-2
Unable to establish connection to http://openshift-master-2.qe1.kni.lab.eng.bos.redhat.com:5050: HTTPConnectionPool(host='openshift-master-2.qe1.kni.lab.eng.bos.redhat.com', port=5050): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c9474ee80>: Failed to establish a new connection: [Errno 111] Connection refused',))

[cloud-user@r640-u01 dev-scripts]$ for i in 0 1 2; do ssh core@openshift-master-${i}.qe1.kni.lab.eng.bos.redhat.com "hostname; sudo crictl ps -a|grep ironic"; done
openshift-master-0.qe1.kni.lab.eng.bos.redhat.com
bdcc410a35ecf       quay.io/metal3-io/ironic-ipa-downloader@sha256:c304f982c1f677a0c715e5b98a97765d5331022bc7cf44a9936c70d62f2966e5          2 hours ago         Exited              ipa-downloader                          0                   ae0c1163c0542
openshift-master-1.qe1.kni.lab.eng.bos.redhat.com
openshift-master-2.qe1.kni.lab.eng.bos.redhat.com

**Comment by achuzhoy** [comment] 2019-07-19 19:18
Using commit ab8359b3e433af60ab126344b10bce4568b49e1b in https://github.com/openshift-metal3/dev-scripts

**Comment by hardys** [comment] 2019-07-22 08:45
After the masters finish bootstrapping, this is expected, because we currently stop ironic-inspector on the host (which probably isn't absolutely necessary, but after https://github.com/openshift-metal3/kni-installer/pull/100 is completed *all* the bootstrap Ironic services become ephemeral, so you should not depend on these services for testing.

https://github.com/openshift-metal3/dev-scripts/blob/master/08_deploy_bmo.sh#L23

After the cluster comes up, and `08_deploy_bmo.sh` gets run ironic will (after some time) start running on one of the masters - you can check which one with the following steps:

```
$ oc get pods --namespace openshift-machine-api
NAME                                           READY   STATUS    RESTARTS   AGE
cluster-autoscaler-operator-6b99577574-nfz58   1/1     Running   0          2d18h
machine-api-controllers-77bfdb4bb6-w7ts2       3/3     Running   0          2d18h
machine-api-operator-5cb95f79b4-nlr22          1/1     Running   5          2d18h
metal3-baremetal-operator-58b4c4d558-qmpm5     9/9     Running   0          2d18h

$  oc describe pod metal3-baremetal-operator-58b4c4d558-qmpm5 --namespace openshift-machine-api | grep "^Node"
Node:               master-2/192.168.111.22
Node-Selectors:  <none>

[shardy@dell-r630-007 dev-scripts]$ export OS_URL=http://172.22.0.3:6385

[shardy@dell-r630-007 dev-scripts]$ openstack baremetal node list
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| UUID                                 | Name               | Instance UUID                        | Power State | Provisioning State | Maintenance |
+--------------------------------------+--------------------+--------------------------------------+-------------+--------------------+-------------+
| 5614f998-7b1b-44ca-bd52-085d3742c9f2 | openshift-master-2 | None                                 | power on    | manageable         | False       |
| a4d3c0d0-da62-474e-8b06-2260048252c8 | openshift-worker-0 | a4d3c0d0-da62-474e-8b06-2260048252c8 | power on    | active             | False       |
| de106e92-9335-41ae-8039-493bdaefdbb8 | openshift-master-0 | None                                 | power on    | manageable         | False       |
| a069a59e-c95b-419b-93ac-f5377c58fd6a | openshift-master-1 | None                                 | power on    | manageable         | False       |
```

Note that the masters are marked manageable until https://github.com/metal3-io/baremetal-operator/pull/263 is completed.  AFAIK that work does not include collecting introspection data for externally provisioned hosts (although we do collect it via terraform), and the plan is for continuous introspection to replicate the deploy-time introspection data, but perhaps @zaneb can confirm.

**Comment by zaneb** [comment] 2019-07-22 13:39
That's the plan AIUI.

I suspect the issue here is that the ironic-inspector container is running but you can't connect to port 5050 from outside the pod in which it is deployed?

**Comment by hardys** [comment] 2019-07-22 13:53
I think the issue is @achuzhoy is trying to connect via the public/ctlplane network, but IIRC we only bind the ironic services to the provisioning interface, e.g the 172.22.0.3 IP (which is currently hard-coded in the BMO configmap that dev-scripts applies, ref https://github.com/openshift-metal3/dev-scripts/pull/676

**Comment by achuzhoy** [comment] 2019-07-22 23:43
After fixing the BMO pod:
[cloud-user@r640-u01 ~]$ oc get pod -n openshift-machine-api 
NAME                                          READY   STATUS             RESTARTS   AGE
cluster-autoscaler-operator-cf969ffc4-46q7b   1/1     Running            0          27m
machine-api-controllers-85fc67ff6c-ckqfq      3/3     Running            0          36m
machine-api-operator-577f585945-2f9fc         0/1     CrashLoopBackOff   7          37m
metal3-baremetal-operator-58b4c4d558-scw6b    9/9     Running            0          21m


[cloud-user@r640-u01 ~]$ OS_URL=http://172.22.0.3:5050 openstack baremetal introspection data save openshift-master-2
Introspection data not found for node 47eb86e9-33f5-4e0f-98f0-c9beb157f6a9, processed=True

So the inspector is reachable, but no introspection data.

**Comment by achuzhoy** [comment] 2019-07-22 23:43
@dtantsur  FYI.

**Comment by russellb** [comment] 2019-07-23 01:32
> machine-api-operator-577f585945-2f9fc 0/1 CrashLoopBackOff 7 37m

Have you looked at why the machine-api-operator pod is in CrashLoopBackOff?  I doubt that's related to what you're reporting here.

Can you explain a bit more about why you're trying to look at ironic-inspector?  I actually thinking looking directly at ironic-inspector at all is the wrong thing to do, unless it's during debugging.  I would never use it for any sort of normal validation.  The design of this system is that 1) Ironic is an implementation detail and 2) that the Ironic database is ephemeral and can be lost at any time.

Right now I would expect the hardware details that come from introspection to be available on a `BareMetalHost` for workers, but not masters.  In either case, ignore what's in Ironic.  What's important is what info made it to the `BareMetalHost`.

**Comment by hardys** [comment] 2019-07-23 07:21
> [cloud-user@r640-u01 ~]$ OS_URL=http://172.22.0.3:5050 openstack baremetal introspection data save openshift-master-2
> Introspection data not found for node 47eb86e9-33f5-4e0f-98f0-c9beb157f6a9, processed=True
> 
> So the inspector is reachable, but no introspection data.

As we discussed yesterday, this is expected because it's referencing a different Ironic-inspector, ultimately this will be fixed via a combination of Ironic adoption of the externally provisioned master nodes (https://github.com/metal3-io/baremetal-operator/issues/185) and continuous introspection (only available when we move to sufficiently new Ironic builds, and apparently there are bugs being worked out atm, perhaps @dtantsur can help with links to those here for reference).

I'll close this out now though, because AFAICT this is working as expected, and there's no bug in dev-scripts to resolve at this time.

**Closed by hardys** 2019-07-23 07:21 UTC
