### ISSUE TITLE
fix_certs.service needs to be wiped during make clean

### ISSUE THREAD

**Issue by djgalloway** [openshift-metal3/dev-scripts#424] opened 2019-04-23 19:10 UTC
**Describe the bug**
`fix_certs.service` isn't wiped during `make clean`/`host_cleanup.sh`.  Subsequent Metal3 deployments fail.

**To Reproduce**
Observed running d5372452cbd015ba24726b40d8ad7d54447c5623

1. Deploy a cluster successfully
2. `make clean`
3. `make`

**Observed behavior**
```
level=debug msg="module.bootstrap.libvirt_ignition.bootstrap: Destruction complete after 0s"
level=debug
level=debug msg="Destroy complete! Resources: 3 destroyed."
level=warning msg="FIXME! Exiting after bootstrap, remove when all operators will come up successfully."
++ dirname ./06_create_cluster.sh
+ sudo systemd-run --on-active=30s --on-unit-active=30m --unit=fix_certs.service ./fix_certs.sh
Failed to start transient timer unit: Unit fix_certs.service already exists.
make: *** [ocp_run] Error 1
```

**Comment by zaneb** [comment] 2019-04-23 19:14
It is stopped in `ocp_cleanup.sh`: https://github.com/openshift-metal3/dev-scripts/blob/master/ocp_cleanup.sh#L8

This has always worked for me.

**Comment by djgalloway** [comment] 2019-04-23 19:24
Oh, you know what?  I set up a cluster, rm'ed the `dev-scripts` dir, then checked out the repo again and ran `make clean` using that new clone.  I'm guessing that won't clean up all the old cluster's artifacts.

I wouldn't expect the cleanup scripts to handle that scenario so we can probably close this.  Sorry for the noise!

**Comment by zaneb** [comment] 2019-04-23 20:03
I'd actually have expected that to work too, but there may be some subtlety that I'm missing in that scenario.

**Comment by hardys** [comment] 2019-05-02 09:03
I think we need more information to help - it's certainly a corner case because there's a bunch of state in the dev-scripts/ocp dir which you removed.  

If you can provide the script logs showing the failure we can perhaps see why the systemctl stop didn't run, but otherwise this should probably be closed as not a bug - we expect make clean to consume the state written to dev-scripts/ocp.

**Comment by zaneb** [comment] 2019-05-02 15:10
Yeah, I think we can just close this. Hopefully the whole fix_certs thing can go away shortly anyway.

**Comment by dhellmann** [comment] 2019-05-07 16:51
It looks like the service is not properly deleted if it is in the "failed" state. That can be reset with "systemctl reset-failed fix_certs" and then the service is cleaned up correctly.

**Closed** 2019-05-07 17:54 UTC
