### ISSUE TITLE
clean machine install: "error creating bridge interface baremetal: File exists"

### ISSUE THREAD

**Issue by jhutar** [openshift-metal3/dev-scripts#808] opened 2019-09-16 12:39 UTC
**Describe the bug**
On a fresh machine, installation fails with "error creating bridge interface baremetal: File exists"

**To Reproduce**
Mine version of dev-scripts:
```
commit ca0d3bc9c6f3e3e9ad9e6f3eefb92299497243f3
Merge: 44b935f ef078a0
Author: Steven Hardy <shardy@redhat.com>
Date:   Tue Sep 10 12:40:08 2019 -0400

    Merge pull request #803 from russellb/rhel8-bz-1750866
```

1. install `CentOS Linux release 7.6.1810 (Core)` on host and upgrade it
2. configure sudo
3. clone https://github.com/openshift-metal3/dev-scripts
4. prepare PULL_SECRET
5. `make`

**Expected/observed behavior**
```
TASK [libvirt : Start libvirt networks] ****************************************
ESC[1;30mtask path: /opt/dev-scripts/metal3-dev-env/vm-setup/roles/libvirt/tasks/network_setup_tasks.yml:39ESC[0m
[...]
ESC[0;31m        "name": "baremetal", ESC[0m
ESC[0;31m        "nat_port_range": [ESC[0m
ESC[0;31m            1024, ESC[0m
ESC[0;31m            65535ESC[0m
ESC[0;31m        ], ESC[0m
ESC[0;31m        "netmask": "255.255.255.0"ESC[0m
ESC[0;31m    }, ESC[0m
ESC[0;31m    "msg": "error creating bridge interface baremetal: File exists"ESC[0m
ESC[0;31m}ESC[0m

PLAY RECAP *********************************************************************
ESC[0;31mlocalhostESC[0m                  : ESC[0;32mok=15  ESC[0m changed=0    unreachable=0    ESC[0;31mfailed=1   ESC[0m ESC[0;36mskipped=7   ESC[0m rescued=0    ignored=0   

make: *** [configure] Error 2
```

Full `make` log: [dev-scripts-make.log](https://github.com/openshift-metal3/dev-scripts/files/3616242/dev-scripts-make.log)

**Additional context**
Looks like (based on github search) this was reported before, but for cleanup scripts. In my case I'm doing clean install.

**Comment by jhutar** [comment] 2019-09-16 12:41
This is the job which is hitting it: https://jenkins-fci-continuous-p.../job/jhutar-simple-pipeline/

**Comment by hardys** [comment] 2019-09-23 10:44
I just installed a fresh centos7 system and cannot reproduce this, do you have any more information or logs I can refer to?  The jenkins job link appears broken?

**Comment by hardys** [comment] 2019-09-30 08:30
No additional information forthcoming so I'll close this, please reopen if you can provide more details @jhutar

**Closed by hardys** 2019-09-30 08:30 UTC
